version: '3.8'

services:
  nodejs:
    build: 
      context: .
      dockerfile: ./docker/node-dev.dockerfile
    env_file:
      - ./.env
    image: r4deu51/nodejs_url_shortener
    container_name: nodejs_url_shortener
    ports:
      - "3000:3000"
    networks:
      - network

networks:
  network: